#!/usr/bin/env python3
"""
Copilot Workflow Runner

This script interprets and executes the copilot.yaml workflow by processing
each step sequentially and applying the corresponding prompt templates.
"""

import os
import sys
import yaml
import json
from pathlib import Path
from typing import Dict, List, Any
import argparse


class CopilotWorkflowRunner:
    def __init__(self, workflow_file: str = "copilot.yaml"):
        self.workflow_file = workflow_file
        self.workflow_dir = Path(os.path.dirname(os.path.abspath(workflow_file)))
        self.workflow_data = {}
        self.context = {}
        
    def load_workflow(self):
        """Load and parse the copilot.yaml file"""
        try:
            with open(self.workflow_file, 'r') as f:
                self.workflow_data = yaml.safe_load(f)
            print(f"✅ Loaded workflow: {self.workflow_data.get('name', 'Unknown')}")
            print(f"📝 Description: {self.workflow_data.get('description', 'No description')}")
        except FileNotFoundError:
            print(f"❌ Error: Could not find {self.workflow_file}")
            sys.exit(1)
        except yaml.YAMLError as e:
            print(f"❌ Error parsing YAML: {e}")
            sys.exit(1)
    
    def load_input_files(self):
        """Load input files specified in the workflow"""
        inputs = self.workflow_data.get('inputs', {})
        
        for input_name, input_config in inputs.items():
            if input_config.get('type') == 'file':
                file_path = input_config.get('default', '')
                if file_path:
                    full_path = self.workflow_dir / file_path
                    try:
                        with open(full_path, 'r', encoding='utf-8') as f:
                            content = f.read()
                        self.context[input_name] = content
                        print(f"✅ Loaded input file: {file_path}")
                    except FileNotFoundError:
                        print(f"❌ Warning: Input file not found: {full_path}")
                        self.context[input_name] = ""
    
    def load_prompt_template(self, prompt_path: str) -> str:
        """Load a prompt template file"""
        full_path = self.workflow_dir / prompt_path
        try:
            with open(full_path, 'r', encoding='utf-8') as f:
                return f.read()
        except FileNotFoundError:
            print(f"❌ Error: Prompt template not found: {full_path}")
            return ""
    
    def execute_step(self, step: Dict[str, Any]) -> str:
        """Execute a single workflow step"""
        step_name = step.get('name', 'Unknown Step')
        prompt_path = step.get('uses', '')
        
        print(f"\n🔄 Executing step: {step_name}")
        print(f"📄 Using prompt: {prompt_path}")
        
        # Load the prompt template
        prompt_template = self.load_prompt_template(prompt_path)
        if not prompt_template:
            return ""
        
        # For demonstration purposes, we'll show the prompt and simulate processing
        print("=" * 60)
        print("PROMPT TEMPLATE:")
        print("=" * 60)
        print(prompt_template[:500] + "..." if len(prompt_template) > 500 else prompt_template)
        
        # In a real implementation, this is where you would:
        # 1. Process the prompt with the current context
        # 2. Call an LLM API (OpenAI, Anthropic, etc.)
        # 3. Get the response and update the context
        
        print("\n" + "=" * 60)
        print("INPUTS FOR THIS STEP:")
        print("=" * 60)
        
        # Show available inputs
        step_inputs = step.get('with', {})
        for key, value in step_inputs.items():
            if isinstance(value, str) and value.startswith('${{ inputs.'):
                # Extract input reference
                input_ref = value.replace('${{ inputs.', '').replace(' }}', '')
                if input_ref in self.context:
                    content = self.context[input_ref]
                    print(f"{key}: {content[:200]}..." if len(content) > 200 else content)
        
        # If no specific inputs, show all available context
        if not step_inputs and self.context:
            for key, value in self.context.items():
                if isinstance(value, str):
                    print(f"{key}: {value[:200]}..." if len(value) > 200 else value)
        
        print("\n" + "=" * 60)
        print("SIMULATED OUTPUT (would be generated by LLM):")
        print("=" * 60)
        
        # Generate a simulated response based on the step
        simulated_output = self.generate_simulated_output(step_name, step)
        print(simulated_output)
        
        # Update context with the output
        output_key = f"step_{len([k for k in self.context.keys() if k.startswith('step_')]) + 1}_output"
        self.context[output_key] = simulated_output
        
        return simulated_output
    
    def generate_simulated_output(self, step_name: str, step: Dict[str, Any]) -> str:
        """Generate simulated output based on the step being executed"""
        
        if "extract deliverables" in step_name.lower():
            return """deliverables:
  - title: "User Authentication API"
    type: "backend"
    description: "RESTful API for user registration, login, and profile management"
    goal: "Provide secure user authentication and profile management capabilities"
    success_criteria:
      - "Supports JWT token-based authentication"
      - "Handles registration, login, and password reset"
      - "Responds under 200ms at p95"
      
  - title: "Product Catalog Service"
    type: "backend"
    description: "Service for managing product listings, search, and inventory"
    goal: "Enable product discovery and inventory management"
    success_criteria:
      - "Supports full-text search with filtering"
      - "Real-time inventory tracking"
      - "Handles 1000+ concurrent searches"
      
  - title: "Payment Processing Integration"
    type: "integration"
    description: "Integration with multiple payment gateways (Stripe, PayPal)"
    goal: "Enable secure payment processing with multiple payment methods"
    success_criteria:
      - "PCI DSS compliant payment processing"
      - "99%+ payment success rate"
      - "Support for credit cards, PayPal, and mobile payments"
      
  - title: "AWS Cloud Infrastructure"
    type: "infra"
    description: "Containerized microservices deployment on AWS with Kubernetes"
    goal: "Provide scalable, highly available cloud infrastructure"
    success_criteria:
      - "Auto-scaling based on load"
      - "99.9% uptime SLA"
      - "Multi-AZ deployment for high availability\""""
        
        elif "map to epics" in step_name.lower():
            return """epics:
  - title: "User Management System"
    summary: "Implement comprehensive user authentication and profile management"
    labels: ["backend", "authentication", "security"]
    complexity: "Medium"
    
  - title: "Product Discovery Platform"
    summary: "Build product catalog with advanced search and filtering capabilities"
    labels: ["backend", "search", "catalog"]
    complexity: "High"
    
  - title: "Payment Gateway Integration"
    summary: "Integrate secure payment processing with multiple providers"
    labels: ["integration", "payment", "security"]
    complexity: "High"
    
  - title: "Cloud Infrastructure Setup"
    summary: "Deploy scalable microservices architecture on AWS"
    labels: ["infra", "aws", "kubernetes"]
    complexity: "Medium\""""
        
        elif "generate stories" in step_name.lower():
            return """user_stories:
  - epic: "User Management System"
    story: "As a customer, I want to register an account so I can make purchases"
    acceptance_criteria:
      - "User can register with email and password"
      - "Email verification is required"
      - "User profile is automatically created"
    story_points: 5
    
  - epic: "User Management System"  
    story: "As a customer, I want to login to my account so I can access my order history"
    acceptance_criteria:
      - "User can login with email/password"
      - "JWT token is issued on successful login"
      - "Session expires after 24 hours"
    story_points: 3
    
  - epic: "Product Discovery Platform"
    story: "As a customer, I want to search for products so I can find what I need"
    acceptance_criteria:
      - "Search supports keywords and filters"
      - "Results are sorted by relevance"
      - "Auto-suggestions appear while typing"
    story_points: 8\""""
        
        elif "acceptance criteria" in step_name.lower():
            return """enhanced_stories:
  - epic: "User Management System"
    story: "As a customer, I want to register an account so I can make purchases"
    acceptance_criteria:
      - "Given I am on the registration page, when I enter valid email and password, then my account is created"
      - "Given I register, when I check my email, then I receive a verification link"
      - "Given I click the verification link, when I return to the site, then my account is activated"
      - "Given invalid email format, when I try to register, then I see appropriate error message"
    story_points: 5
    test_scenarios:
      - "Happy path registration"
      - "Email verification flow"
      - "Invalid email format handling"
      - "Duplicate email registration attempt\""""
        
        elif "dependencies" in step_name.lower():
            return """dependencies:
  - story: "User registration"
    depends_on: []
    blocks: ["User login", "User profile management"]
    
  - story: "User login"
    depends_on: ["User registration"]
    blocks: ["Order placement", "Order history viewing"]
    
  - story: "Product search"
    depends_on: ["Product catalog setup"]
    blocks: ["Add to cart functionality"]
    
  - story: "Payment processing"
    depends_on: ["User login", "Shopping cart"]
    blocks: ["Order confirmation"]\""""
        
        elif "jira" in step_name.lower():
            return """jira_payload:
  epics:
    - key: "ECOM-100"
      summary: "User Management System"
      description: "Implement comprehensive user authentication and profile management"
      issue_type: "Epic"
      labels: ["backend", "authentication", "security"]
      
  stories:
    - key: "ECOM-101"
      summary: "User Registration Feature"
      description: "As a customer, I want to register an account so I can make purchases"
      issue_type: "Story"
      epic_link: "ECOM-100"
      story_points: 5
      acceptance_criteria: |
        - Given I am on the registration page, when I enter valid email and password, then my account is created
        - Given I register, when I check my email, then I receive a verification link
        
csv_format: |
  Issue Type,Summary,Description,Epic Link,Story Points,Labels
  Epic,User Management System,Implement comprehensive user authentication and profile management,,,"backend,authentication,security"
  Story,User Registration Feature,As a customer I want to register an account so I can make purchases,User Management System,5,backend\""""
        
        else:
            return f"Simulated output for step: {step_name}"
    
    def execute_workflow(self):
        """Execute the complete workflow"""
        print(f"\n🚀 Starting workflow execution: {self.workflow_data.get('name', 'Unknown')}")
        
        # Load input files
        self.load_input_files()
        
        # Execute each step
        steps = self.workflow_data.get('steps', [])
        outputs = []
        
        for i, step in enumerate(steps, 1):
            print(f"\n{'='*80}")
            print(f"STEP {i}/{len(steps)}: {step.get('name', 'Unknown Step')}")
            print(f"{'='*80}")
            
            output = self.execute_step(step)
            outputs.append({
                'step_name': step.get('name'),
                'step_number': i,
                'output': output
            })
        
        # Save workflow results
        self.save_results(outputs)
        
        print(f"\n✅ Workflow execution completed!")
        print(f"📊 Results saved to: workflow_results.json")
        
    def save_results(self, outputs: List[Dict[str, Any]]):
        """Save workflow results to a file"""
        results = {
            'workflow_name': self.workflow_data.get('name'),
            'workflow_description': self.workflow_data.get('description'),
            'execution_steps': outputs,
            'final_context': self.context
        }
        
        output_file = self.workflow_dir / 'workflow_results.json'
        with open(output_file, 'w', encoding='utf-8') as f:
            json.dump(results, f, indent=2, ensure_ascii=False)


def main():
    parser = argparse.ArgumentParser(description='Execute a copilot.yaml workflow')
    parser.add_argument('--workflow', '-w', default='copilot.yaml',
                        help='Path to the copilot.yaml file (default: copilot.yaml)')
    parser.add_argument('--verbose', '-v', action='store_true',
                        help='Enable verbose output')
    
    args = parser.parse_args()
    
    print("🤖 Copilot Workflow Runner")
    print("=" * 40)
    
    # Create and run the workflow
    runner = CopilotWorkflowRunner(args.workflow)
    runner.load_workflow()
    runner.execute_workflow()


if __name__ == "__main__":
    main()